### ISSUE TITLE
Empty Edit Page on Wordpress Version 6.1.1

### ISSUE THREAD

**Issue by VpsOP** [KevinBatdorf/code-block-pro#105]
Hi, I am using the latest v1.11.2 of the plugin.
When using the plugin to show the HTML code it shows an empty edit post page.

STEPS TO REPRODUCE:
1. Make a New Post
2. Add some HTML CODE with links and Scripts
3. Publish it.
4. Now reload the editor.
5. The editor does not show anything and there are errors in the console.

Could you have a quick look into the issue?

I am using this code to be shown in the block:
```html
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bootstrap 5</title> 
    
    <!-- Include JS for Bootstrap 5 (PopperJS + BootstrapJS) -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"></script>
    
    <!-- Include Bootstrap 5 CSS Definitions-->
    <link 
        rel="stylesheet" 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" 
    />
</head>

```

**Comment by KevinBatdorf** [comment]
Thanks for reporting this. Can you try out this build here? If it's working then I'll make a release today with the update. 

https://github.com/KevinBatdorf/code-block-pro/actions/runs/3867783869

![Screen Shot 2023-01-08 at 10 39 28 AM](https://user-images.githubusercontent.com/1478421/211205539-948669aa-d561-4b45-97c7-56da0033c795.png)
