### ISSUE TITLE
Adding DAX and PowerQuery

### ISSUE THREAD

**Issue by Aksiyom** [KevinBatdorf/code-block-pro#112]
Hi,
could you pls add DAX and PowerQuery language support?

thanks

**Comment by KevinBatdorf** [comment]
Let me look into it this week. Do you know of a VS code plugin that adds the language support? I can get the file from that most likely.

**Comment by Aksiyom** [comment]
this migjht help for both languages

https://prismjs.com/download.html#themes=prism&languages=dax+powerquery

**Comment by KevinBatdorf** [comment]
I need the textmate grammar file actually. Maybe this one will work though for power query:

https://github.com/microsoft/powerquery-language

For DAX nothing turned up in a quick search. If it's being highlighted in VS Code though (through an extension or natively) then I should be able to find it somewhere.

**Comment by Aksiyom** [comment]
I am not that much experienced in scripting Kevin, currently using  syntax highlighter evolved WP plugin with additional DAX brush script, which u can download from the second link in my reply.

this is a sample page with the DAX language if it helps https://powerbi.istanbul/numerik-sutunlari-boyut-olarak-tasarlamak/

**Comment by KevinBatdorf** [comment]
That does help, thanks. I'll follow up when I have something.

**Comment by KevinBatdorf** [comment]
I've submitted [a PR upstream](https://github.com/shikijs/shiki/pull/422) to add the two language grammars. I'll make a release, likely over the weekend. I'll follow up again then.

**Comment by KevinBatdorf** [comment]
These are now live in v1.12! Thanks for the request

**Comment by Aksiyom** [comment]
thanks Kevin 👍
