### ISSUE TITLE
Kusto KQL

### ISSUE THREAD

**Issue by SimonSkotheimsvik** [KevinBatdorf/code-block-pro#116]
Could it be possible to add support for Kusto/KQL queries?

**Comment by KevinBatdorf** [comment]
It's possible but I have to submit a PR upstream and I'm not sure when they will make a release with the update. I'll follow up here when it's ready though

Does this styling look right? https://marketplace.visualstudio.com/items?itemName=rosshamish.kuskus-kusto-syntax-highlighting

**Comment by SimonSkotheimsvik** [comment]
Hi Kevin,
That styling you referred looks right. It would have been great to have this included. 
Thanks for following this up!

**Comment by KevinBatdorf** [comment]
Submitted a PR upstream and when they release it I'll be able to add it to the next plugin release. Hard to know when that will be exactly but I'll update here (they could also reject the PR too though, so it depends).

https://github.com/shikijs/shiki/pull/431

**Comment by SimonSkotheimsvik** [comment]
Thanks for following up. I see the case has been closed as completed, but I can't see the Kusto/KQL available as an option yet?
https://wordpress.org/plugins/code-block-pro/

**Comment by KevinBatdorf** [comment]
Sorry for the delay. They tagged it in the release yesterday so I updated it today. If you're still looking to use this plugin, it supports kql now! Thanks for the suggestion
