### ISSUE TITLE
[Improvement] Move css to external file

### ISSUE THREAD

**Issue by kienmatu** [KevinBatdorf/code-block-pro#136]
## Problems:
I used the plugin [CodeSyntax block](https://github.com/mkaz/code-syntax-block) before, but It doesn't have many features like `code block pro` (CBP).

CodeSyntax block **It has an advantage** compared with CBP: SEO
- The CSS file size is smaller (**1.3kb** for the default theme), and this will definitely affect SEO.
- In addition, the default CSS file will be cached by the browser

It's not necessary for me to use multiple code themes. I just need one and put the CSS into an external file.

Now can we add an option into Code Block Pro settings, that it will use just one theme and load css externally by default ?

**Comment by KevinBatdorf** [comment]
WordPress seems to be handling that automatically. I wasn't aware actually. I'll look into it. 

The stylesheet that gets enqueued though is 2.7kb and used for adding the copy button and various minor things. I can probably get this file smaller though by compressing the class prefixes. You can also just remove this file entirely. You don't need it except for padding around the `pre` tag.

It's not theme styles though, which are inlined line by line within a style attribute.

> The CSS file size is smaller (1.3kb for the default theme), and this will definitely affect SEO.

I really can't see this being an accurate claim. Regardless, I'll look into it.

**Comment by kienmatu** [comment]
Thank you!
