### ISSUE TITLE
[Feature request] Dark mode with tailwind

### ISSUE THREAD

**Issue by kienmatu** [KevinBatdorf/code-block-pro#142]
My WordPress theme is using tailwindcss, and I use darkmode for it (by class).
So I just wonder whether we can just have default settings that contains:
- Default dark theme
- Default light theme

For the github light theme, its background is white, and my web's background is white also, It is a little bad UI, I think we can add a small solid border into it:
![Screenshot from 2023-03-17 15-15-50](https://user-images.githubusercontent.com/38078992/225849999-d7e9af18-107a-4eb6-9158-271642cde08c.png)

Another UI improvement I think it could be better is the border-radius, currently, it's just 0 with `!important`, and I just can change the radius of the header, not the body.

Thank you!

**Comment by KevinBatdorf** [comment]
I need to keep those overrides to stop other theme styles from adding their own borders, etc. Ideally WP blocks would have style controls for borders, border radius, etc or the theme would via theme.json. 

I can give you some CSS though to override anything you'd like though if you want to share your page. Often it's just a matter of css specificity. You can add a div in front of it, or another class, and also use `!important`

For light/dark, in the paid theme [add-on pack](https://code-block-pro.com/) (that currently just includes more themes), I'm going to add a way to build your own themes, which will include an option to use _no theme_ and let you define css variables instead. With this you will be able to update the variables via media query. I probably need another 2-3 weeks though as I'm traveling until next week.

**Comment by KevinBatdorf** [comment]
I forgot to comment here but it's technically possible to do this now. Here's a guide: https://github.com/KevinBatdorf/code-block-pro/discussions/168
