### ISSUE TITLE
Can you add GDScript?

### ISSUE THREAD

**Issue by zkmark** [KevinBatdorf/code-block-pro#166]
Can you add GDScript?

It is the programming language of the Godot Engine, an engine for creating video games.

**Comment by KevinBatdorf** [comment]
Sure! I'm using [shiki](https://github.com/shikijs/shiki) which added the language last week. They just need to tag a new release then I can pull in gdscript, gdresource, and gdshader. I have no idea when they will tag a release though

**Comment by KevinBatdorf** [comment]
This was added today! Let me know if you have any issues using it (sorry for the delay)
