### ISSUE TITLE
All spaces are removed on solidity

### ISSUE THREAD

**Issue by keesmark** [KevinBatdorf/code-block-pro#173]
When writing in the edit.  
![スクリーンショット 2023-04-19 7 22 39](https://user-images.githubusercontent.com/26785257/232918134-4d56f3cf-2fac-4eec-851a-d25becc574bd.png)

After post block.
![スクリーンショット 2023-04-19 7 23 43](https://user-images.githubusercontent.com/26785257/232918232-cf8bc95f-6743-45a4-85f3-2d03e9ccd30f.png)

**Comment by KevinBatdorf** [comment]
I just tested it locally and it's working. Could it be another theme or some CSS that's doing it? Can you share a URL?

**Comment by keesmark** [comment]
Thanks for your reply!
Here is some sample page URL.
https://jp.0xkeesmark.com/me/

**Comment by KevinBatdorf** [comment]
Something somewhere is changing the content, likely on the server before it gets to the page. Do you have another syntax highlighting plugin active? Could it be from your theme?

Look at the difference in mark up. Yours is on the left. Something else is parsing it.

![Screen Shot 2023-04-18 at 8 05 00 PM](https://user-images.githubusercontent.com/1478421/232930603-e6936949-874c-4ffa-8094-b7d8f09604f5.png)

**Comment by keesmark** [comment]
Thanks for the details. I found out that my theme has a highlight plugin. That's why the issue came up.

**Comment by KevinBatdorf** [comment]
What theme? Maybe I can disable it for others that install the plugin

**Comment by keesmark** [comment]
Oh really? But it is a Japanese one. Is it ok?  
The theme name is cocoon.
https://wp-cocoon.com/downloads/

**Comment by KevinBatdorf** [comment]
Not sure but I can check ☺️

**Comment by KevinBatdorf** [comment]
I took a look at the code. It looks like there's an option to disable it in the theme settings. If you want to, maybe you can look in the theme settings.
 
Otherwise, this filter should work (I think. I didn't test it, I only inspected the code). I thought about adding it to the plugin, but since the theme isn't hosted on w.org it's not the best idea.

```php
// Add to functions.php
add_filter("theme_mod_code_highlight_enable", '__return_false');
```

**Comment by keesmark** [comment]
I can disable the plugin with the filter code. But it still hasn't worked. It may cause other things.  
Anyway, thanks for helping! I will look at other themes or just use another way.
