### ISSUE TITLE
Classic Editor Support? Wolfram Mathematica Language Syntax Highlighting Support?

### ISSUE THREAD

**Issue by HomayoonT** [KevinBatdorf/code-block-pro#174]
It seems the Code Block Pro does not support [Wordpress classic editor](https://wordpress.org/plugins/classic-editor/). Is it possible to have classic editor support?
In addition, the syntax highlighter does not support the [Wolfram Mathematica language](https://www.wolfram.com/mathematica/).

**Comment by KevinBatdorf** [comment]
No plans for classic editor support mainly because I want it to remain light and forward-looking. I'd have to introduce server-side processing otherwise. 

For the Wolfram lang, is this the sort of highlighting you'd expect? https://marketplace.visualstudio.com/items?itemName=WolframResearch.wolfram

**Comment by HomayoonT** [comment]
> No plans for classic editor support mainly because I want it to remain light and forward-looking. I'd have to introduce server-side processing otherwise.
> 
> For the Wolfram lang, is this the sort of highlighting you'd expect? https://marketplace.visualstudio.com/items?itemName=WolframResearch.wolfram

That is the official Wolfram Language Visual Studio Code extension ( The best they could implement for VSCode ). So my answer is yes.

**Comment by KevinBatdorf** [comment]
Added Wolfram to today's release! Let me know if any issues with it

**Comment by HomayoonT** [comment]
> Added Wolfram to today's release! Let me know if any issues with it

![Wolfram](https://user-images.githubusercontent.com/74807046/235421256-87a0ec75-ad8c-4978-ab62-56e12e0fa682.png)

Basically whatever theme I select when I select `Wolfram` as the language I get the error `Theme X not found`.

I don't have this problem after selecting other languages such as Python.

**Comment by KevinBatdorf** [comment]
Sorry, I had a typo in the language key. Fixed in https://github.com/KevinBatdorf/code-block-pro/pull/183 

I'll push a release now in about 15 minutes
