### ISSUE TITLE
How to insert code in pure HTML mode?

### ISSUE THREAD

**Issue by DoctorLai** [KevinBatdorf/code-block-pro#175]
Hello,
can't find the tutorial on how to insert the code in pure HTML editor of wordpress.
for example,
I like to do this:

<pre>
&lt;pre lang=rust&gt;
// some rust code
&lt;/pre&gt;
</pre>

I don't see any plugin settings in wordpress dashboard.
Thanks.

**Comment by KevinBatdorf** [comment]
There isn't one. You have to use the block. The reason is that it processes the formatting as you type, so there is no server or frontend processing. I want the plugin to have negligible overhead so it doesn't slow down anyone's site.
