### ISSUE TITLE
White colored after inserting dollar sign ($) on a line

### ISSUE THREAD

**Issue by HomayoonT** [KevinBatdorf/code-block-pro#176]
Browser: Firefox 112.0.1 (64-bit)
OS: Windows 10

For instance I type the following line in Wordpress editor for CMake language
![InEditor](https://user-images.githubusercontent.com/74807046/233852816-262a6e62-d874-4430-b314-19469ee6fcaf.png)

Then I go to the Wordpress preview and that's what I get

![InPreview](https://user-images.githubusercontent.com/74807046/233852837-49980e49-83c7-45ef-92a6-88b916483622.png)

As you can see the dollar sign disappears and the whole line becomes white colored.

**Comment by KevinBatdorf** [comment]
It's going to be something in your theme, or another plugin server overriding the output. In some cases it could also be CSS related, but given the `$` is missing, it's likely not that.

If you can share a link I can maybe look for a clue

**Comment by HomayoonT** [comment]
> It's going to be something in your theme, or another plugin server overriding the output. In some cases it could also be CSS related, but given the `$` is missing, it's likely not that.
> 
> If you can share a link I can maybe look for a clue

You are right. It was the [WP QuickLaTeX](http://www.holoborodko.com/pavel/quicklatex/) plugin conflicting with your plugin.
It tries to render mathematical formulas written in LaTeX. It simply uses `$` sign to render LaTeX. I had to exclude it in the config.

![Excluded](https://user-images.githubusercontent.com/74807046/233854733-e374b4df-2730-44c2-81ce-e2699fd6dd6c.png)

So for future references, use `\(` f(x)=x^2 `\)` and `\[` f(x)=x^2 `\]` respectively instead of `$` f(x)=x^2 `$` and `$$` f(x)=x^2 `$$` for [rendering math formulas in inline or display math mode](https://www.overleaf.com/learn/latex/Mathematical_expressions).
