### ISSUE TITLE
Filter the language fast for language selection

### ISSUE THREAD

**Issue by HomayoonT** [KevinBatdorf/code-block-pro#177]
I wish the area (select language) I have highlighted was a text box in which I could type the first letter of the language of I want to find then it would filter the list, like I would type `A` and the list of languages would become restricted to the languages starting with the `A` letter.

![FilterLang](https://user-images.githubusercontent.com/74807046/234198482-0929067d-be2f-4bb8-a28b-10dd50094b6e.png)

I have found that for switching languages I have to scroll through the list every time.

**Comment by KevinBatdorf** [comment]
It's a limitation of that WordPress component. I agree though and also dislike it. I was thinking actually to remove it entirely. 

You can select the language from the sidebar settings instead. From there you can type the letter, or I keep the 3 most recent languages there as buttons for quick changing. Have you seen that in the sidebar?

**Comment by KevinBatdorf** [comment]
I removed this in today's release. If you press the language now it will open up the sidebar panel (same for clicking on the theme now too)
