### ISSUE TITLE
Code-block has margins!

### ISSUE THREAD

**Issue by vandadnp** [KevinBatdorf/code-block-pro#181]
Hi and thank you for this WP plugin

While editing the code-block in WP, I can see the block rendered fine as shown here:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/759524/235404717-e36c4650-2d09-4a66-9928-a54ab4805bba.png">

But when viewing it in my website it looks like this:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/759524/235404734-73df204d-6406-4a5a-b57f-a469d2746c58.png">

After inspecting the layer in the middle I can see that it has margins

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/759524/235404809-7f138cd5-f244-4878-ab00-cc5d09f3d14e.png">

Which it probably has inherited from my WP theme or some other object above it. The fix would be to set explicit 0x margins on the code-block itself. Thank you in advance.

Note also how line-numbers are not rendered even though they are enabled.

**Comment by KevinBatdorf** [comment]
Thanks for bringing this up. Could you share a link? It could also be another script attempting to process the code block.

That lines render as span tags and I can see in that screenshot it has display of block, so something is going on.

**Comment by vandadnp** [comment]
Hi Kevin and thank you for the prompt reply

I unfortunately cannot provide you with the website URL at the time being since it's a dev environment on WP and not available to the public. Is there any other diagnostics details that I can provide you with that might help you?

Thanks again

**Comment by KevinBatdorf** [comment]
No problem. A screenshot of the elements panel from the browser devtools with some of the code expanded would probably work. Maybe highlight on a span so I can see what css is being added. 

Or is the theme publicly available? I could just install it and see what's happening. 

It could also be another plugin that is filtering the html. Could you try disabling all other plugins and see if there's a change?

**Comment by KevinBatdorf** [comment]
That comment doesn't really make sense or even address anything at all. It's just kind of random. Is that on an open forum? I can chime in if so. 

It's most likely something from your theme (is that memberpress?) that is running and extra script or some server formatting. Can you check their options page for something to disable? You can also confirm this by switching themes for a minute to check.

If not, disable all plugins, check, then turn them back on one by one until the problem comes back.

If you can share a screenshot like this I can maybe identify based on the formatting what is causing it.

![Screen Shot 2023-05-03 at 9 16 19 AM](https://user-images.githubusercontent.com/1478421/235927764-2754c817-d2ef-4f6a-ae60-a70aed81620d.png)

**Comment by vandadnp** [comment]
Hi Kevin and thanks for your response

That's what I was afraid of! No it's a support chat with a member of the MemberPress support team so it's not an open discussion unfortunately. I've tested Code Block Pro on a normal page on my site and it looks beautiful. It's only when you render it within MemberPress pages that it doe
<img width="1920" alt="Screenshot 2023-05-04 at 04 47 31" src="https://user-images.githubusercontent.com/759524/236100911-a0084156-7617-4c2b-b5b6-ab51fa151cbb.png">
sn't look good.

Here is the screenshot that you requested, and once again thanks for taking your time looking at this.

As you can see in the screenshot, the font is wrong (too large), there are margins that shouldn't be there, and line numbers, even though enabled, are not rendered.

**Comment by KevinBatdorf** [comment]
Can you try your site in an incognito browser? Or disable the Dark Reader extension and try

**Comment by vandadnp** [comment]
You bet, here it is
<img width="1920" alt="Screenshot 2023-05-04 at 05 26 34" src="https://user-images.githubusercontent.com/759524/236106460-80d766c8-001e-424d-9b56-6a96df18c1ec.png">

**Comment by vandadnp** [comment]
If you feel it can be of help, I have nothing against jumping on a Google Meets call with you so you can diagnose it in person. Just let me know if that's preferable for you.

**Comment by KevinBatdorf** [comment]
The stylesheet isn't loading at all actually. This sounds like a "feature" in memberpress they _should fix asap_. Now I see what they meant by inline. I thought they meant inline by the style attribute on an element (`<div styles="">`), but they meant using an inline style tag (in the document `<head><style>`). 

(Maybe your best best it to share this comment with them)

This is actually native WordPress core functionality and not something from code in the plugin. WordPress will inline css style for gutenberg blocks. If memeberpress is disabling that by default then I'm sure no custom blocks that have styles are loading for any of their users.

The code reference in core is here: https://github.com/WordPress/WordPress/blob/master/wp-includes/script-loader.php#L2371

I can't really see why they would be removing these styles under any circumstance though anyway, but maybe there's a way to disable that from an optimization setting or a CSS setting somewhere.

**Comment by vandadnp** [comment]
Thank you for your response Kevin, I've relayed your message to the MemberPress support team and will wait for their response. Have a lovely rest of the day.

**Comment by vandadnp** [comment]
Hi again Kevin, I've been in contact with MemberPress about this and from what I can see the solution was for them to go into WPEngine's "Code Snippets" section and add your styles in there according to this file: https://github.com/KevinBatdorf/code-block-pro/blob/main/src/front/style.css

So they copy pasted that file into WPEngine's "Code Snippets" section and it's looking much better but we are still having issues with font sizes but I think it's a MemberPress issue, not Code Block Pro's

Thank you for your help so you can close this issue if you want to. I appreciate your time.

**Comment by KevinBatdorf** [comment]
Are they not loading the JavaScript file too?

When you get the site online somewhere I'll be happy to take a look and see what's missing.

**Comment by vandadnp** [comment]
Which JS file is that? Is it this one? https://github.com/KevinBatdorf/code-block-pro/blob/main/src/front/front.js

**Comment by KevinBatdorf** [comment]
Yeah that one, although it would be minified like this:

```js
(()=>{var e={640:(e,t,o)=>{"use strict";var r=o(742),a={"text/plain":"Text","text/html":"Url",default:"Text"};e.exports=function(e,t){var o,n,c,s,l,i,d=!1;t||(t={}),o=t.debug||!1;try{if(c=r(),s=document.createRange(),l=document.getSelection(),(i=document.createElement("span")).textContent=e,i.ariaHidden="true",i.style.all="unset",i.style.position="fixed",i.style.top=0,i.style.clip="rect(0, 0, 0, 0)",i.style.whiteSpace="pre",i.style.webkitUserSelect="text",i.style.MozUserSelect="text",i.style.msUserSelect="text",i.style.userSelect="text",i.addEventListener("copy",(function(r){if(r.stopPropagation(),t.format)if(r.preventDefault(),void 0===r.clipboardData){o&&console.warn("unable to use e.clipboardData"),o&&console.warn("trying IE specific stuff"),window.clipboardData.clearData();var n=a[t.format]||a.default;window.clipboardData.setData(n,e)}else r.clipboardData.clearData(),r.clipboardData.setData(t.format,e);t.onCopy&&(r.preventDefault(),t.onCopy(r.clipboardData))})),document.body.appendChild(i),s.selectNodeContents(i),l.addRange(s),!document.execCommand("copy"))throw new Error("copy command was unsuccessful");d=!0}catch(r){o&&console.error("unable to copy using execCommand: ",r),o&&console.warn("trying IE specific stuff");try{window.clipboardData.setData(t.format||"text",e),t.onCopy&&t.onCopy(window.clipboardData),d=!0}catch(r){o&&console.error("unable to copy using clipboardData: ",r),o&&console.error("falling back to prompt"),n=function(e){var t=(/mac os x/i.test(navigator.userAgent)?"⌘":"Ctrl")+"+C";return e.replace(/#{\s*key\s*}/g,t)}("message"in t?t.message:"Copy to clipboard: #{key}, Enter"),window.prompt(n,e)}}finally{l&&("function"==typeof l.removeRange?l.removeRange(s):l.removeAllRanges()),i&&document.body.removeChild(i),c()}return d}},742:e=>{e.exports=function(){var e=document.getSelection();if(!e.rangeCount)return function(){};for(var t=document.activeElement,o=[],r=0;r<e.rangeCount;r++)o.push(e.getRangeAt(r));switch(t.tagName.toUpperCase()){case"INPUT":case"TEXTAREA":t.blur();break;default:t=null}return e.removeAllRanges(),function(){"Caret"===e.type&&e.removeAllRanges(),e.rangeCount||o.forEach((function(t){e.addRange(t)})),t&&t.focus()}}}},t={};function o(r){var a=t[r];if(void 0!==a)return a.exports;var n=t[r]={exports:{}};return e[r](n,n.exports,o),n.exports}o.n=e=>{var t=e&&e.__esModule?()=>e.default:()=>e;return o.d(t,{a:t}),t},o.d=(e,t)=>{for(var r in t)o.o(t,r)&&!o.o(e,r)&&Object.defineProperty(e,r,{enumerable:!0,get:t[r]})},o.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t),(()=>{"use strict";var e=o(640),t=o.n(e);const r=".wp-block-kevinbatdorf-code-block-pro",a=()=>{Array.from(document.querySelectorAll(`${r}:not(.cbp-see-more-loaded) .cbp-see-more-line`)).forEach((e=>{const t=e.closest(r);t.classList.add("cbp-see-more-loaded");const o=e.closest("pre"),a=o.offsetHeight;let n=0;if(e.classList.contains("cbp-see-more-transition")){const t=o.querySelectorAll("code > *").length,r=Array.from(e.closest("code").children).filter((t=>t.offsetTop<e.offsetTop))?.length;n=.5+.01*(t-r),o.style.transition=`max-height ${n}s ease-out`}const c="SPAN"===t.children[0].tagName?t.children[0].offsetHeight:0,s=parseFloat(window.getComputedStyle(e).lineHeight);o.style.maxHeight=e.offsetTop+s-c+"px";const l=e.closest(r).querySelector(".cbp-see-more-container");if(!l)return;l.style.display="flex";const i=l.querySelector(".cbp-see-more-simple-btn");if(!i)return;t.classList.contains("padding-disabled")&&i.classList.remove("cbp-see-more-simple-btn-hover"),i.style.transition=`all ${Math.max(n,1)/1.5}s linear`;const d=e=>{e.preventDefault(),i.classList.remove("cbp-see-more-simple-btn-hover"),o.style.maxHeight=a+"px",setTimeout((()=>{i.style.opacity=0,i.style.transform="translateY(-100%)",setTimeout((()=>i.remove()),1e3*Math.max(n,1))}),1e3*n)};i.addEventListener("click",d),i.addEventListener("keydown",(e=>{"Enter"===e.key&&d(e)}))})),Array.from(document.querySelectorAll(".code-block-pro-copy-button:not(.cbp-cb-loaded)")).forEach((e=>{e.classList.add("cbp-cb-loaded"),e.style.display="block";const o=e=>{var o;const{type:r,key:a,target:n}=e;if("keydown"===r&&!["Enter"," "].includes(a))return;e.preventDefault();const c=n?.closest("span");t()(null!==(o=c?.dataset?.code)&&void 0!==o?o:"",{format:"text/plain"}),c.classList.add("copying"),setTimeout((()=>{c.classList.remove("copying")}),2e3)};["click","keydown"].forEach((t=>e.addEventListener(t,o)))})),Array.from(document.querySelectorAll(`${r} pre:not(.cbp-hl-loaded)`)).forEach((e=>{e.classList.add("cbp-hl-loaded");const t=e.querySelectorAll(".cbp-line-highlight");t.length&&(new ResizeObserver((t=>{t.forEach((t=>{e.style.setProperty("--cbp-block-width","0");const o=t.target.querySelector("code").offsetWidth,r=o+16===t.target.scrollWidth?o+16:t.target.scrollWidth+16;e.style.setProperty("--cbp-block-width",`${r}px`)}))})).observe(e),t.forEach((e=>{e.insertAdjacentHTML("beforeend",'<span aria-hidden="true" class="cbp-line-highlighter"></span>')})))})),(()=>{if(!window.codeBlockPro?.pluginUrl)return;const e=Array.from(document.querySelectorAll("[data-code-block-pro-font-family]:not(.cbp-ff-loaded)")||[]);e.forEach((e=>e.classList.add("cbp-ff-loaded"))),[...new Set(e.map((e=>e.dataset.codeBlockProFontFamily)).filter(Boolean))].forEach((async e=>{const t=new FontFace(e,`url(${window.codeBlockPro.pluginUrl}/build/fonts/${e}.woff2)`);await t.load(),document.fonts.add(t)}))})()};a(),window.codeBlockProInit=a,window.addEventListener("DOMContentLoaded",a),window.addEventListener("load",a)})()})();
```

But on line [76](https://github.com/KevinBatdorf/code-block-pro/blob/main/src/front/front.js#L76) is where it loads in the fonts.

**Comment by vandadnp** [comment]
Hi Kevin,

Thanks for your help. I can see the JS file is getting loaded. Looking at the styles, the only block I can see that is setting the `font-size` is this:

```css
.wp-block-kevinbatdorf-code-block-pro pre * {
    font-size: inherit !important;
    line-height: inherit !important
}
```

So if the plugin that is rendering the page, in this case MemberPress, changes the font, then Code Block Pro will inherit that font size instead of the default Wordpress fonts, right?

Would it be possible to have font-sizes built into the styles or am I thinking crooked here?

**Comment by KevinBatdorf** [comment]
I'm afk today but I did add a clamp setting somewhere. It would be nearby where the font is set, which I think is under the styling tab. Could try that first. 

Otherwise I'd have to see it to see what's happening.

**Comment by KevinBatdorf** [comment]
I think this was resolved but if not please reopen!
