### ISSUE TITLE
Language request: Vyper language

### ISSUE THREAD

**Issue by dpanosian** [KevinBatdorf/code-block-pro#182]
Can you please add support for Vyper language?
[https://docs.vyperlang.org/en/stable/](url)

**Comment by KevinBatdorf** [comment]
Thanks for the suggestion. Do you use VS Code? Is this the highlighter you would use?

https://github.com/tintinweb/vscode-vyper

**Comment by dpanosian** [comment]
Yes! IMO that's the best one for Vyper for VSCode.

**Comment by KevinBatdorf** [comment]
Languages need to be added upstream so I made a PR for it there (https://github.com/shikijs/shiki/pull/466). When they tag a new release I'll add it here asap and follow up.
