### ISSUE TITLE
Language Request: Cypher

### ISSUE THREAD

**Issue by ajskelton** [KevinBatdorf/code-block-pro#185]
Could you add the Neo4j Cypher query language?

https://neo4j.com/docs/getting-started/cypher-intro/

There is an official VS Code extension that includes the syntax highlighting https://marketplace.visualstudio.com/items?itemName=adamcowley.neo4j-vscode

**Comment by KevinBatdorf** [comment]
Thanks for the request! Languages I need to PR upstream, which I've done here (https://github.com/shikijs/shiki/pull/465). As soon as they make a release I'll add it in and follow up here
