### ISSUE TITLE
Plugin adds color hexcodes to the tags of a post

### ISSUE THREAD

**Issue by aadilayub** [KevinBatdorf/code-block-pro#195]
Hi! Thanks for making this elegant plugin.

I just tried out and noticed [my posts with code blocks in them](https://aadils.computer/tag/generative-art/) got tagged with a bunch of random color hexcodes? I didn't add them myself, so I can only assume they were added by the plugin.

![image](https://github.com/KevinBatdorf/code-block-pro/assets/31581044/5467a138-50ef-40e8-ae2e-73164e8a91ee)

Is there a way to disable this?

**Comment by KevinBatdorf** [comment]
Interesting. Those are colors used in the theme? 

Do you possibly have another plugin that is attempting to auto tag based on the content?

**Comment by aadilayub** [comment]
Yep, it seems like they're colors from the syntax theme. The tags change if I change the syntax theme. I'm using several plugins, but as far as I can tell, none of them have an auto-tagging feature.

**Comment by KevinBatdorf** [comment]
That's probably it. It's reading the color codes as if they are hash tags. Can you disable it and confirm?

**Comment by aadilayub** [comment]
Disabled it and removed the tags from all the posts. Hopefully they won't show up again like before 🤞🏼

**Comment by aadilayub** [comment]
They're not showing up anymore, so that settles it. Thanks for your support! I'll add an issue in the activitypub plugin repo for this.

**Comment by wadetregaskis** [comment]
Still broken in the latest version of ActivityPub. 😔
