### ISSUE TITLE
[bug] HTML entity is automatically converted

### ISSUE THREAD

**Issue by adriancs2** [KevinBatdorf/code-block-pro#196]
When typing a HTML entity in the code block pro editor, for example, it's automatically converted this
```
&amp;
```
to
```
&
```
This happens on other HTML entities as well, such as:
```
&lt;    becomes "<"
&gt;    becomes ">"
&nbsp;  becomes " "
&copy;  becomes "©"
```
I'm wondering is it possible to maintain the HTML entity code while editing?

Here are my thoughts, in order to correctly pass the code for rendering, there are 3 crucial characters that once they are encoded, the text should be safe for syntax highlight rendering. The 3 characters are `&`, `<` and `>`.

I'm not sure how your code works in behind, but I would like to share my idea of handling this. 

Assuming that the primary text editing is happening in a textarea, then, we can escaped the characters like this:
```javascript
let textarea1 = documenet.getElementById("textarea1");
let content = textarea1.value;
    
// encode the special characters
content = content.replace(/&/g, '&amp;');
content = content.replace(/</g, '&lt;');
content = content.replace(/>/g, '&gt;');

let renderedText = DoSyntaxHighlightRendering(content);
```
If the user intentionally entered the symbol "&" for whatever reason (either intentionally for typing the HTML entity), it will be encoded to loss the original meaning of "&" in HTML.

So, which means, if the user type the following:
```
&amp;  &lt;  &gt;
```
It will be encoded as follow
```
&amp;amp;  &amp;lt;  &amp;gt;
```
and will be sent to the rendering engine for syntax highlightning.

Hope this help :)

**Comment by KevinBatdorf** [comment]
Thanks for reporting this! I'll make it an option (under extra settings) and put it in the next release in the next day or two
