### ISSUE TITLE
Font Request - Jetbrains Mono NL

### ISSUE THREAD

**Issue by MegaJerk** [KevinBatdorf/code-block-pro#212]
I didn't see an easy way to add a custom font to this wonderful plugin, so I would like to request the addition of the Non-Ligature version of the Jetbrains Mono font if possible.

Thank you

**Comment by KevinBatdorf** [comment]
Hey, thanks for the suggestion and sponsor! I'll add it this weekend! Let me know if anything else you find missing from the plugin.
