### ISSUE TITLE
Difference in copied XML-code to original

### ISSUE THREAD

**Issue by pglu** [KevinBatdorf/code-block-pro#222]
[230726 issue difference in XML-code.zip](https://github.com/KevinBatdorf/code-block-pro/files/12175899/230726.issue.difference.in.XML-code.zip)

The copied code that comes out of the code-block is different from the original. Thus it cannot be read by my editor https://mach.pglu.ch (for testing, go to 'Code > XML-Code' and paste code. Then click 'in Grafik umwandeln' to see the generated blocks). 
I have analyzed the original and the copy with a text comparison tool and send you the detected errors in the attachment. However, I don't know if there are other differences in other cases.

**Comment by KevinBatdorf** [comment]
Can you go under Extra Settings and enable html entities? I strip those out as a security measure (it's WordPress, so I default to extra security) but you can opt-in on each block.

![Screen Shot 2023-07-26 at 4 05 12 PM](https://github.com/KevinBatdorf/code-block-pro/assets/1478421/dd3ed41d-feb3-40bb-a36c-4ceb9e2ec64f)

It's a bit annoying to opt-in on every block, but in the future, WP will add reusable block patterns that can be synced, and when they do I'll utilize those more for reusable settings. 

If that doesn't work let me know and I'll investigate further

**Comment by pglu** [comment]
I made the setting, but it causes the block to crash. I can't undo the setting after that and have to add the block again. See this video: https://vimeo.com/848985515/742aef54a9?share=copy

**Comment by pglu** [comment]
There is another strange behavior of the block: when I right click "select all", the last part of the code is not selected. It is also not selectable manually. 
Looking closely, I see that the last code part is a repetition of the part before it (it ends right with ..</XML>). If you move the mouse over the text at the end of the selectable area, then it changes to other text. 
I hope I have described it well.

See video: https://vimeo.com/848986569/89cb89b944?share=copy

**Comment by KevinBatdorf** [comment]
Can you take a look and see if this is working properly? https://tests.kevinbatdorf.com/test-xml-encoding/

You can also test it by downloading the artifact here: https://github.com/KevinBatdorf/code-block-pro/actions/runs/5685517932

However, you need to set press the button to enable "Allow HTML Entities" in Extra Settings before you enter any code, as pressing it after will decode it first.

**Comment by pglu** [comment]
Works perfect, thank you!

**Comment by KevinBatdorf** [comment]
Great, thanks! If you want to use that plugin artifact I linked to it will work fine when updating and I'll add the changes to the next release as well (probably Sunday)

**Comment by KevinBatdorf** [comment]
I made the release just now. If you used the artifact file above, you may actually need to go back to the code, make a small change like a ` ` character, then save it again. I had to add some of the previous implementation back to avoid an edge case breaking for others that may have this option set.

If you have any issues though let me know and I'll happily take another look. Thanks!
