### ISSUE TITLE
Browser parsing issue causing DoS for the editor

### ISSUE THREAD

**Issue by irsdl** [KevinBatdorf/code-block-pro#225]
Although this issue may not be directly related to this plugin, I never had this issue before using this extension so I think we might be able to address the issue here.

In a blog post I had an example with `<!-- something here -->` HTML code and later on I had an example with `<script>...</script>`. After highlighting these two code (they are separate in my case, see https://soroush.me/blog/2019/08/uploading-web-config-for-fun-and-profit-2/), the editor at `/wp-admin/post.php?post=[id]&action=edit` stopped working.
The reason is that whilst it encode `-->` to `--&gt;`, it does not encode `<!--` and `<script ` which makes it to break completely. 

Here is an example of what's happening here and why it is breaking the page: https://security.stackexchange.com/questions/192931/why-does-script-in-a-js-string-cause-a-broken-page-denial-of-service-for 

I think the solution is to also encode `<!--` but I am not sure why this is only happening after this plugin is used.

**Comment by KevinBatdorf** [comment]
It should encode both. Do you have a code sample that breaks it? I tried some on that page you linked to and the stackoverflow page but they worked for me.

![Screen Shot 2023-07-27 at 6 54 36 PM](https://github.com/KevinBatdorf/code-block-pro/assets/1478421/da88c1a0-db43-4a79-a988-f7925ee2e7f1)

It could be another plugin interfering too. I see you have [SyntaxHighlighter Evolved](https://wordpress.org/plugins/syntaxhighlighter/) enabled too. Can you disable that and try it (even just to rule it out)? If that is causing the conflict, I may be able to patch it.

**Comment by irsdl** [comment]
For me `<!--` and `<script ` (with the space after) are in separated sections. 

I have attached what I have in the database for the post_content field. Perhaps you can inject it to the database to see how it breaks the page.  You probably need to escape `<script ` to actually see it in WordPress and it seems after saving it becomes broken again. The `<!-- ` can be part of the highlighting template as well (e.g. `<!-- wp:kevinbatdorf/code-block-pro `) so they don't need to be put there by users.

[post_content.txt](https://github.com/KevinBatdorf/code-block-pro/files/12188958/post_content.txt)

**Comment by KevinBatdorf** [comment]
I can see it's being escaped twice.  I'm not sure why, but its typically best to first try and rule out other plugins.

For comparison, here's how it should be represented in the database: [post_content.txt](https://github.com/KevinBatdorf/code-block-pro/files/12189649/v.txt)

I can try to reproduce it. Can you give a list of the plugins you are using? 

Can you also give an example code snippet that definitely breaks down? Or is this one? [example.txt](https://github.com/KevinBatdorf/code-block-pro/files/12189669/u.txt)

And are you on the latest version of WordPress?

**Comment by irsdl** [comment]
I am having a hard time recreating this using a new post. Originally this happened when I had an existing post with "Code" parts and I wanted to convert them to `Code Pro`. I also had `SyntaxHighlighter Code` extension but all was converted to `Code Pro`

Now I am thinking whether this bug occurs because of conversions so here are my tests at the moment which show some other potential bugs as well:

* Test 1
  1.1- Creating a simple code block with:
```
html here foobar
<!-- foobar -->
<script src="/test">
alert(1);
// some more code
</script>
<!-- some more -->
<script>
alert(2);
</script>
```
![image](https://github.com/KevinBatdorf/code-block-pro/assets/1798313/e130eb90-ca1a-46e5-99bb-174236d6a5cb)

1.2- Converting it to `Code Pro` by using the `Transform To` panel:
![image](https://github.com/KevinBatdorf/code-block-pro/assets/1798313/b8fcca6c-4a69-46fd-976e-3205d468563c)
![image](https://github.com/KevinBatdorf/code-block-pro/assets/1798313/b2ca4d68-63cd-4891-94df-0a20e73831db)

1.3- Converting it back to `Code` by using the `Transform To` panel:
![image](https://github.com/KevinBatdorf/code-block-pro/assets/1798313/4ce7c0d9-ee92-4330-9da3-72304c302b83)
![image](https://github.com/KevinBatdorf/code-block-pro/assets/1798313/c80135e2-4c87-4fda-9bc0-3bd1f581ba0e)

** So here is another bug creating the wrong code **
1.4- Converting it back to `Code Pro` by using the `Transform To` panel:
![image](https://github.com/KevinBatdorf/code-block-pro/assets/1798313/bf18faf5-0bb3-48c6-b0df-356b1fd1b4d8)
![image](https://github.com/KevinBatdorf/code-block-pro/assets/1798313/44a8fe47-aa11-4bf4-b77e-875cfa0a187f)
all looks fine after converting it back again.

1.5- saving/updating the post
1.6- reloading the editor will show a blank page due to errors:
![image](https://github.com/KevinBatdorf/code-block-pro/assets/1798313/0c967b7b-06fc-49ce-9bfb-341110a7de8c)
![image](https://github.com/KevinBatdorf/code-block-pro/assets/1798313/4f3da97f-2b8c-469a-a414-2aa78900b4c3)

This is what has been written in the database:
```
'<!-- wp:paragraph -->\n<p>This is a test for the highlighter extensions</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:kevinbatdorf/code-block-pro {\"code\":\"html here foobar\\n\\u003c!\\u002d\\u002d foobar \\u002d\\u002d\\u003e\\n\\u003cscript src=\\u0022/test\\u0022\\u003e\\nalert(1);\\n// some more code\\n\\u003c/script\\u003e\\n\\u003c!\\u002d\\u002d some more \\u002d\\u002d\\u003e\\n\\u003cscript\\u003e\\nalert(2);\\n\\u003c/script\\u003e\\n\",\"codeHTML\":\"\\u003cpre class=\\u0022shiki monokai\\u0022 style=\\u0022background-color: #272822\\u0022 tabindex=\\u00220\\u0022\\u003e\\u003ccode\\u003e\\u003cspan class=\\u0022line\\u0022\\u003e\\u003cspan style=\\u0022color: #F8F8F2\\u0022\\u003ehtml here foobar\\u003c/span\\u003e\\u003c/span\\u003e\\n\\u003cspan class=\\u0022line\\u0022\\u003e\\u003cspan style=\\u0022color: #88846F\\u0022\\u003e\\u0026lt;!\\u002d\\u002d foobar \\u002d\\u002d\\u0026gt;\\u003c/span\\u003e\\u003c/span\\u003e\\n\\u003cspan class=\\u0022line\\u0022\\u003e\\u003cspan style=\\u0022color: #F8F8F2\\u0022\\u003e\\u0026lt;\\u003c/span\\u003e\\u003cspan style=\\u0022color: #F92672\\u0022\\u003escript\\u003c/span\\u003e\\u003cspan style=\\u0022color: #F8F8F2\\u0022\\u003e \\u003c/span\\u003e\\u003cspan style=\\u0022color: #A6E22E\\u0022\\u003esrc\\u003c/span\\u003e\\u003cspan style=\\u0022color: #F8F8F2\\u0022\\u003e=\\u003c/span\\u003e\\u003cspan style=\\u0022color: #E6DB74\\u0022\\u003e\\u0026quot;/test\\u0026quot;\\u003c/span\\u003e\\u003cspan style=\\u0022color: #F8F8F2\\u0022\\u003e\\u0026gt;\\u003c/span\\u003e\\u003c/span\\u003e\\n\\u003cspan class=\\u0022line\\u0022\\u003e\\u003cspan style=\\u0022color: #F8F8F2\\u0022\\u003ealert(1);\\u003c/span\\u003e\\u003c/span\\u003e\\n\\u003cspan class=\\u0022line\\u0022\\u003e\\u003cspan style=\\u0022color: #F8F8F2\\u0022\\u003e// some more code\\u003c/span\\u003e\\u003c/span\\u003e\\n\\u003cspan class=\\u0022line\\u0022\\u003e\\u003cspan style=\\u0022color: #F8F8F2\\u0022\\u003e\\u0026lt;/\\u003c/span\\u003e\\u003cspan style=\\u0022color: #F92672\\u0022\\u003escript\\u003c/span\\u003e\\u003cspan style=\\u0022color: #F8F8F2\\u0022\\u003e\\u0026gt;\\u003c/span\\u003e\\u003c/span\\u003e\\n\\u003cspan class=\\u0022line\\u0022\\u003e\\u003cspan style=\\u0022color: #88846F\\u0022\\u003e\\u0026lt;!\\u002d\\u002d some more \\u002d\\u002d\\u0026gt;\\u003c/span\\u003e\\u003c/span\\u003e\\n\\u003cspan class=\\u0022line\\u0022\\u003e\\u003cspan style=\\u0022color: #F8F8F2\\u0022\\u003e\\u0026lt;\\u003c/span\\u003e\\u003cspan style=\\u0022color: #F92672\\u0022\\u003escript\\u003c/span\\u003e\\u003cspan style=\\u0022color: #F8F8F2\\u0022\\u003e\\u0026gt;\\u003c/span\\u003e\\u003c/span\\u003e\\n\\u003cspan class=\\u0022line\\u0022\\u003e\\u003cspan style=\\u0022color: #F8F8F2\\u0022\\u003ealert(2);\\u003c/span\\u003e\\u003c/span\\u003e\\n\\u003cspan class=\\u0022line\\u0022\\u003e\\u003cspan style=\\u0022color: #F8F8F2\\u0022\\u003e\\u0026lt;/\\u003c/span\\u003e\\u003cspan style=\\u0022color: #F92672\\u0022\\u003escript\\u003c/span\\u003e\\u003cspan style=\\u0022color: #F8F8F2\\u0022\\u003e\\u0026gt;\\u003c/span\\u003e\\u003c/span\\u003e\\n\\u003cspan class=\\u0022line\\u0022\\u003e\\u003c/span\\u003e\\u003c/code\\u003e\\u003c/pre\\u003e\",\"language\":\"xml\",\"theme\":\"monokai\",\"bgColor\":\"#272822\",\"textColor\":\"#F8F8F2\",\"fontSize\":\".875rem\",\"fontFamily\":\"\",\"lineHeight\":\"1rem\",\"clampFonts\":false,\"lineNumbers\":false,\"headerType\":\"headlights\",\"highlightingHover\":false,\"lineHighlightColor\":\"rgba(253, 253, 237, 0.2)\",\"copyButton\":true,\"copyButtonType\":\"twoSquares\"} -->\n<div class=\"wp-block-kevinbatdorf-code-block-pro\" data-code-block-pro-font-family=\"\" style=\"font-size:.875rem;line-height:1rem\"><span style=\"display:block;padding:16px 0 0 16px;margin-bottom:-1px;width:100%;text-align:left;background-color:#272822\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"54\" height=\"14\" viewBox=\"0 0 54 14\"><g fill=\"none\" fill-rule=\"evenodd\" transform=\"translate(1 1)\"><circle cx=\"6\" cy=\"6\" r=\"6\" fill=\"#FF5F56\" stroke=\"#E0443E\" stroke-width=\".5\"></circle><circle cx=\"26\" cy=\"6\" r=\"6\" fill=\"#FFBD2E\" stroke=\"#DEA123\" stroke-width=\".5\"></circle><circle cx=\"46\" cy=\"6\" r=\"6\" fill=\"#27C93F\" stroke=\"#1AAB29\" stroke-width=\".5\"></circle></g></svg></span><span role=\"button\" tabindex=\"0\" data-code=\"html here foobar\n<!-- foobar --&gt;\n<script src=&quot;/test&quot;&gt;\nalert(1);\n// some more code\n</script&gt;\n<!-- some more --&gt;\n<script&gt;\nalert(2);\n</script&gt;\n\" style=\"color:#F8F8F2;display:none\" aria-label=\"Copy\" class=\"code-block-pro-copy-button\"><svg xmlns=\"http://www.w3.org/2000/svg\" style=\"width:24px;height:24px\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" stroke-width=\"2\"><path class=\"with-check\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4.5 12.75l6 6 9-13.5\"></path><path class=\"without-check\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M16.5 8.25V6a2.25 2.25 0 00-2.25-2.25H6A2.25 2.25 0 003.75 6v8.25A2.25 2.25 0 006 16.5h2.25m8.25-8.25H18a2.25 2.25 0 012.25 2.25V18A2.25 2.25 0 0118 20.25h-7.5A2.25 2.25 0 018.25 18v-1.5m8.25-8.25h-6a2.25 2.25 0 00-2.25 2.25v6\"></path></svg></span><pre class=\"shiki monokai\" style=\"background-color: #272822\" tabindex=\"0\"><code><span class=\"line\"><span style=\"color: #F8F8F2\">html here foobar</span></span>\n<span class=\"line\"><span style=\"color: #88846F\">&lt;!-- foobar --&gt;</span></span>\n<span class=\"line\"><span style=\"color: #F8F8F2\">&lt;</span><span style=\"color: #F92672\">script</span><span style=\"color: #F8F8F2\"> </span><span style=\"color: #A6E22E\">src</span><span style=\"color: #F8F8F2\">=</span><span style=\"color: #E6DB74\">&quot;/test&quot;</span><span style=\"color: #F8F8F2\">&gt;</span></span>\n<span class=\"line\"><span style=\"color: #F8F8F2\">alert(1);</span></span>\n<span class=\"line\"><span style=\"color: #F8F8F2\">// some more code</span></span>\n<span class=\"line\"><span style=\"color: #F8F8F2\">&lt;/</span><span style=\"color: #F92672\">script</span><span style=\"color: #F8F8F2\">&gt;</span></span>\n<span class=\"line\"><span style=\"color: #88846F\">&lt;!-- some more --&gt;</span></span>\n<span class=\"line\"><span style=\"color: #F8F8F2\">&lt;</span><span style=\"color: #F92672\">script</span><span style=\"color: #F8F8F2\">&gt;</span></span>\n<span class=\"line\"><span style=\"color: #F8F8F2\">alert(2);</span></span>\n<span class=\"line\"><span style=\"color: #F8F8F2\">&lt;/</span><span style=\"color: #F92672\">script</span><span style=\"color: #F8F8F2\">&gt;</span></span>\n<span class=\"line\"></span></code></pre></div>\n<!-- /wp:kevinbatdorf/code-block-pro -->\n\n<!-- wp:paragraph -->\n<p></p>\n<!-- /wp:paragraph -->'
```

Size of this post is also very big as the style is being applied to every tag rather than as a CSS for the whole code snippet.

I am also thinking that it can potentially cause a XSS issue (if post editors should not run JS by default - not the case for me as I am admin).

**Comment by irsdl** [comment]
BTW. I am using the latest version of WP and plugins.

**Comment by irsdl** [comment]
My workaround so far is to:
1- deactivate the extension
2- edit the post
3- save/update the post by making a small change
4-reactivate the extension
5- refresh the edit page
6- recover highlighted blocks and save/update the post
7- while remaining in the edit page, add a space or a non-important character to all snippets causing the original issue and save/update again!

**Comment by KevinBatdorf** [comment]
Thanks for this write up! So the issue seems to be when converting from the WordPress code block into the Code Pro block? I can take a look at that. I'll test out the snippet you provided and follow up with something later today. 

But on new posts, would you say everything is working fine?

> Size of this post is also very big as the style is being applied to every tag rather than as a CSS for the whole code snippet.

That's a fair observation. It's mainly just how the library ([Shiki](https://github.com/shikijs/shiki)) that powers the highlighting works. I could write a custom parser for it to scope and combine the styles in a more optimized way like youre alluding to. I'll add it to the todo list.

**Comment by irsdl** [comment]
I followed those steps in a new post. So it seems all should be fine if we are not using conversions and use Code Pro initially. Sometimes it also crashes my browser tab when using the preview in the Transform To section hovering the Code Pro but that's another issue ;)
