### ISSUE TITLE
Themes not found after last update

### ISSUE THREAD

**Issue by davidemariani** [KevinBatdorf/code-block-pro#230]
After the last update I can't use code block pro anymore and I am getting the following message

<img width="775" alt="Screenshot 2023-07-31 at 22 07 54" src="https://github.com/KevinBatdorf/code-block-pro/assets/32668547/799b3999-9f59-49a8-ab61-76605c00a1d3">

**Comment by KevinBatdorf** [comment]
I just tried it on a fresh site and it seems ok. Any chance the update failed? Can you delete the plugin and install it again?

**Comment by KevinBatdorf** [comment]
Also, I guess that message could show if there's a specific error with the webassembly module failing to load. Can you check the browser console for any errors and share them here if any?

**Comment by davidemariani** [comment]
Initially deleting and re-installing the plugin did not work, but today it is working as it should. Not sure what was happening, but all good now!

**Comment by KevinBatdorf** [comment]
Maybe some old browser cache or something like that was conflicting. Thanks for the follow up! If you notice any issues in the future let me know.
