### ISSUE TITLE
Feature request: code folding

### ISSUE THREAD

**Issue by MartinLBarron** [KevinBatdorf/code-block-pro#238]
Wonderful plugin. Thanks for creating it.  It fills a desperate need I had.

One feature I might suggest: code folding.  The ability to specify a maximum height of the code block is great, but sometimes readers want to collapse a code chunk completely.  The ability of the author to add a button that would collapse the block to just, say, the header, would be a welcome addition.

An example of a code folding feature implemented by a non-wordpress application can be found here: https://quarto.org/docs/output-formats/html-code.html#folding-code

**Comment by KevinBatdorf** [comment]
Thanks for the nice words! Have you tried using a details block and adding the code block to that?

https://wordpress.org/documentation/article/details-block/

**Comment by MartinLBarron** [comment]
Oh, gosh, I didn't know detail-blocks were a thing.  Works perfectly and solves my problem.  Thanks!
