### ISSUE TITLE
How to turn on wrap

### ISSUE THREAD

**Issue by sunnyk21** [KevinBatdorf/code-block-pro#257]
Hi
wondering how to turn on wrapping instead of long horizontal line of code with scroll bar

Great plugin btw, love the theme options

**Comment by KevinBatdorf** [comment]
I can give you some custom CSS for it. It might not work properly with every feature though, for example, line highliting.

You can check this issue for some custom css, or also share a URL and I'll check it out.

https://github.com/KevinBatdorf/code-block-pro/issues/221

**Comment by sunnyk21** [comment]
that worked! I am not using line highlighting and getting the desired results

Thankyou
