### ISSUE TITLE
Broken in Spacing

### ISSUE THREAD

**Issue by febryanvaldo** [KevinBatdorf/code-block-pro#260]
Hello there,

First of all, i love your work plugin, please keep it up! 

Currently i have a problem with your plugin, which the spacing is not correctly rendered on Front End, while in the back end (Admin Area / Editor), the spacing is just right, no issue at all. Right now i'm using WAMP to host the WordPress, and using Free BreakDance builder (Builder + Theme). If you still confused, please take a look at my screenshots below.

Front End: https://static.kangserver.id/ws9ej.png
Back End: https://static.kangserver.id/xwexw.png

Could you replicate this on your end? You can try download BreakDance builder, as it's free, and please try on your own. Thanks.

Additional Infos;
```
### wp-core ###

version: 6.3.2
site_language: en_US
user_language: en_US
timezone: +07:00
permalink: /%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: C:\wamp\www\breakdance
wordpress_size: loading...
uploads_path: C:\wamp\www\breakdance/wp-content/uploads
uploads_size: loading...
themes_path: C:\wamp\www\breakdance/wp-content/themes
themes_size: loading...
plugins_path: C:\wamp\www\breakdance/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Breakdance Zero Theme (breakdance-zero)
version: 1.0.0
author: Breakdance Builder
author_website: https://breakdance.com/
parent_theme: none
theme_features: core-block-patterns, menus, widgets-block-editor, post-thumbnails, title-tag
theme_path: C:\wamp\www\breakdance\wp-content\plugins\breakdance/plugin/themeless/themes/breakdance-zero
auto_update: Disabled


### wp-plugins-active (6) ###

Advanced Custom Fields PRO: version: 6.2.2, author: WP Engine, Auto-updates disabled
Breakdance: version: 1.6.0-rc.1, author: Breakdance, Auto-updates disabled
Code Block Pro: version: 1.24.1, author: Kevin Batdorf, Auto-updates disabled
Code Snippets: version: 3.5.0, author: Code Snippets Pro, Auto-updates disabled
Perfmatters: version: 2.1.8, author: forgemedia, Auto-updates disabled
WPvivid Backup Plugin: version: 0.9.92, author: WPvivid Team, Auto-updates disabled

### code-snippets (2) ###

snippet-5: name: Perfmatters Fade-in Speed, scope: global, modified: 2023-10-31 08:58:06
snippet-6: name: Disable All WP Generate Images, scope: global, modified: 2023-10-31 08:57:47

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 128M
max_effective_size: 8 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache/2.4.54 (Win64) PHP/8.1.13 mod_fcgid/2.3.10-dev
php_version: 8.1.13 64bit
php_sapi: cgi-fcgi
max_input_variables: 2500
time_limit: 120
memory_limit: 512M
max_input_time: 60
upload_max_filesize: 128M
php_post_max_size: 8M
curl_version: 7.77.0 OpenSSL/1.1.1s
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false
current: 2023-11-01T07:56:47+00:00
utc-time: Wednesday, 01-Nov-23 07:56:47 UTC
server-time: 2023-11-01T14:56:45+07:00

### wp-database ###

extension: mysqli
server_version: 8.0.31
client_version: mysqlnd 8.1.13
max_allowed_packet: 67108864
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: C:\wamp\www\breakdance/wp-content
WP_PLUGIN_DIR: C:\wamp\www\breakdance/wp-content/plugins
WP_MEMORY_LIMIT: 512M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
```

**Comment by KevinBatdorf** [comment]
It looks like extra spaces are being added in. Strange. Do you have the site online? I could probably see what's going on just by looking at the source in the browser.

What if you switch the theme? Any change?

**Comment by febryanvaldo** [comment]
Hello,

It's weird, i don't see it again, as i make the website live, but why only happen in WAMP, i just don't understand.
Website: https://bd.kangserver.id/index.php/benchmark/vps-hyubula-2-cores-amd-4gb-ram-nl-8-eur-2023

**Comment by KevinBatdorf** [comment]
Hmm yeah that's odd. If you could share some screenshots of the source as the browser sees it maybe there is some indicator of the problem.

Btw if you wanted to copy the terminal output with the control sequences you could use the ANSI language setting and it would colorize the output. It would look broken in the editor but the frontend would look right

**Comment by febryanvaldo** [comment]
Hey, looks like the problem already solved, idk what happen, in my localhost (WAMP) the spacing just right, no error anymore, as i fresh installed the WordPress.

Look at here: https://static.kangserver.id/0xdqn.png

> Btw if you wanted to copy the terminal output with the control sequences you could use the ANSI language setting and it would colorize the output. It would look broken in the editor but the frontend would look right

Hmm, i'm afraid i can't do this. I need something neat hahaha.

**Comment by febryanvaldo** [comment]
Hello sir, please check email `sunrise@code-block-pro.com`. You can close this issue, as it's already resolved. Thanks.
