### ISSUE TITLE
Operators in the python program are treated as html entity

### ISSUE THREAD

**Issue by Dev-NeelPrakash** [KevinBatdorf/code-block-pro#261]
Hi Kelvin,

First of all i would like to express my gratitude for development of such a wonderful plugin. I am facing an issue over with this plugin, whenever i use <= or >= != operators in my code, the plugin treats them as html entity and change the formatting. can you please help. Thanks.

![code 2](https://github.com/KevinBatdorf/code-block-pro/assets/149937702/3f1e8572-24ca-4c88-90cc-a9bd0c645461)
![code 1](https://github.com/KevinBatdorf/code-block-pro/assets/149937702/3b197d48-1ca1-4593-8ff3-25bc87ba357c)

**Comment by Dev-NeelPrakash** [comment]
Ok I figured out, Above issue occurs if font type is JetBrains Mono, changed the font type for now. Thanks.

**Comment by Dev-NeelPrakash** [comment]
I figured out, it occurs only if the font type is JetBrains Mono, changed the font for now. Thanks.

**Comment by KevinBatdorf** [comment]
Hey, yeah those are actually font ligatures. Some people like them, some don't. I've included a few fonts without ligatures you can try out, including "JetBrains Mono (No Ligatures)"
