### ISSUE TITLE
Randomly large font sizes on mobile devices

### ISSUE THREAD

**Issue by abctaylor** [KevinBatdorf/code-block-pro#273]
Hi, in Safari on iOS, some lines in code blocks appear very large whilst others not. There is no clear pattern. I'm using "ANSI" for the highlighting. For example:

https://blog.abctaylor.com/kubernetes-on-prem-ha-setup-guide/

![IMG_6037](https://github.com/KevinBatdorf/code-block-pro/assets/30197206/c639778e-be35-4b3a-ab83-9ab54cc5583b)

Is this a known bug?

**Comment by abctaylor** [comment]
Interestingly if I edit the post on a mobile device, all looks fine in the editor view:

![IMG_6038](https://github.com/KevinBatdorf/code-block-pro/assets/30197206/dc84aeb1-dfb6-4fa3-82ad-c261a5d9d7ce)

**Comment by abctaylor** [comment]
Setting all blocks to `bash` which is not "experimental" doesn't help either. Using other major languages like `java`, `c` and `php` make no difference. In one case, with Java, some enlarged variables go italic, but said whole line still remains larger than others.

This looks super bad on mobile devices. I'd personally love to buy the paid version of the extension but I can't if this issue will be there too.

**Comment by abctaylor** [comment]
Playing with various font sizes under `Font styling` doesn't fix this either. Trying a few other fonts also doesn't help sadly.

**What does help:** shorter lines. When lines are "long", something happens to them and makes them big.

**Comment by KevinBatdorf** [comment]
Thanks for reporting this. Can you try adding this to your CSS somewhere? If it works I'll add it to the next release.

```css
div[class*='code-block-pro']:not(.x) pre {
    -webkit-text-size-adjust: 100%
}
```

The issue is on mobile it's making longer lines more readable, which I guess is typically good, but not in this case where the lines should be uniform.

**Comment by abctaylor** [comment]
Did I add this in the right place? WP made it a one-liner like `div[class*='code-block-pro']:not(.x) pre {     -webkit-text-size-adjust: 100% }` and it appeared to not make a difference. Hoping I did something wrong!

<img width="247" alt="image" src="https://github.com/KevinBatdorf/code-block-pro/assets/30197206/1d1a934c-8bd1-4b07-b86b-7917c6f8b155">

In Chrome Dev viewing as "iPhone 12 Pro" it looks fine. But even if I enter bogus CSS it still looks fine.
<img width="372" alt="image" src="https://github.com/KevinBatdorf/code-block-pro/assets/30197206/abe3b004-8a75-42c6-bec9-0fc44223d172">

Here's part of the DOM
<img width="896" alt="image" src="https://github.com/KevinBatdorf/code-block-pro/assets/30197206/e436495f-ec2c-4595-96ab-9b95dd3a5fc1">

**Comment by KevinBatdorf** [comment]
You added it as a class but you need to add it as a style. Can you add it to your theme's stylesheet?

Otherwise I can probably push an update before the end of the week if you can wait a bit.

**Comment by abctaylor** [comment]
Done and the above CSS **fixes it** :)
