### ISSUE TITLE
More options for the Copy button

### ISSUE THREAD

**Issue by bugnumber9** [KevinBatdorf/code-block-pro#274]
It would be great to have more options for the Copy button to make it more distinct.
For example, a pill-shaped button with "Copy" text, etc.
At this point it's hardly even visible in the most themes and doesn't have a tooltip or something to designate it better.

**Comment by KevinBatdorf** [comment]
I can add one. Do you have an example in mind you saw elsewhere?

**Comment by bugnumber9** [comment]
I've been thinking about something like this:
![image](https://github.com/KevinBatdorf/code-block-pro/assets/1769548/3c410485-5074-4334-b466-1ec7cae86608)

Another option:
![image](https://github.com/KevinBatdorf/code-block-pro/assets/1769548/312ba736-95c2-4a84-ae46-9d56aab36912)

**Comment by KevinBatdorf** [comment]
Looks good. I'll see what i can do. I'll follow up when I have something

**Comment by KevinBatdorf** [comment]
Added something similar to the second one. if you wanted to custom style it I could help with that. Just let me know.

PR was here: https://github.com/KevinBatdorf/code-block-pro/pull/279
