### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by bugnumber9** [KevinBatdorf/code-block-pro#275]
I'm sure many will appreciate an option to add custom fonts.
While I like JetBrains Mono or Fira Code, sometimes it makes sense to inherit theme fonts or even plug a custom one in.

**Comment by KevinBatdorf** [comment]
Do you have one in mind? I could add it if it's programming related and uses an open license. 

Otherwise I could give you some css to apply it globally in your theme.

**Comment by bugnumber9** [comment]
Check https://www.sitepoint.com/top-10-programming-fonts/
Roboto Mono, Hack and Melso are good candidates.

**Comment by KevinBatdorf** [comment]
I'll take a look. If they have an open source license and look good when I add them then it shouldn't be an issue including them.
