### ISSUE TITLE
Plaintext drops themes

### ISSUE THREAD

**Issue by technoogies** [KevinBatdorf/code-block-pro#283]
Howdy,

When I select Plaintext, the theme in the block says, "Theme light-plus not found. Please select a different theme.", no matter the theme selected.

- Cory C.

**Comment by KevinBatdorf** [comment]
Thanks for reporting. I'll try to fix that in the next day or so.

**Comment by KevinBatdorf** [comment]
Going to make a release in a few minutes that should fix this. Thanks again
