### ISSUE TITLE
<=, >=, ==, != symbols are replaced by WordPress

### ISSUE THREAD

**Issue by andyli0123** [KevinBatdorf/code-block-pro#313]
<img width="500" alt="symbol-problem" src="https://github.com/KevinBatdorf/code-block-pro/assets/21230214/65f8cda6-d0d3-44cb-be06-5020e62d8d71">

This issue also occurs on a clean WordPress site (with only the Code Block Pro plugin installed and using WordPress’s default theme).

**Comment by KevinBatdorf** [comment]
It's actually the font rendering with ligatures. You can chose a font that doesn't have ligatures in the settings area for the block.

**Comment by andyli0123** [comment]
Solved, thank you!
