### ISSUE TITLE
Plugin stops working after copying the Pro themes

### ISSUE THREAD

**Issue by starborn1701** [KevinBatdorf/code-block-pro#322]
The plugin works without any problems. However, after installing the pro themes (copying _all_ the files from the zip to the plugin directory) the plugin stops working. It is not possible to use it in the editor after that.

**Comment by KevinBatdorf** [comment]
The pro themes is a plugin you need to install just like any other plugin. Is that what you mean?

What was the error? Are you able to delete it to get back into your site?

**Comment by starborn1701** [comment]
Yes, that was the error. Thanks.

**Comment by KevinBatdorf** [comment]
Okay great, let me know if there's anything else
