### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by tomcoady** [KevinBatdorf/code-block-pro#326]
Sorry I can't find the settings in either wordpress of the plugin description!

**Comment by KevinBatdorf** [comment]
Hi. If you go into the Gutenberg editor you can select the block called "Code Pro" or start typing `/code` 

Let me know if still not working

**Comment by tomcoady** [comment]
Hello Kevin,

Thank you for the guidance on using the Gutenberg editor. I followed your
instructions and selected the "Code Pro" block as you suggested. Everything
seems to be working smoothly now.

I appreciate your help! I finally discovered the screen shot of the code
preference under gutenberg blocks so suggest making this more prominent or
describe elsewhere. In any case I really appreciate the functionality,
appearance and ease of use of your plug-in, not to mention the flexibility
and autodetection!

Best regards,

**Comment by KevinBatdorf** [comment]
Thanks for the feedback. I added a bit more instructions near the top for the next person.
