### ISSUE TITLE
Shows up weirdly

### ISSUE THREAD

**Issue by r4881t** [KevinBatdorf/code-block-pro#337]
I am using the theme "Independent Publisher 2" by "By [Raam Dev](http://raamdev.com/)" which is available at URL https://[your wordpress site]/wp-admin/theme-install.php?theme=independent-publisher-2

I have Code Block Pro Installed.

When I type a code, I can see it working correctly in the editor
<img width="1119" alt="Screenshot 2024-09-19 at 12 51 41 PM" src="https://github.com/user-attachments/assets/4ceac0f5-6da2-408d-8d82-9719807b0745">

However when I publish see the output as below

<img width="913" alt="Screenshot 2024-09-19 at 12 49 34 PM" src="https://github.com/user-attachments/assets/f2a45e0f-9a62-466a-a236-670821920a61">

**Comment by r4881t** [comment]
Resolved. I had another code syntax plugin that was conflicting. When I removed others it worked fine

**Comment by KevinBatdorf** [comment]
Thanks for that feedback. Which plugin was it? Maybe I can add some code to prevent interference while trying out this one.
