### ISSUE TITLE
code direction issue in 1.26.5 update

### ISSUE THREAD

**Issue by amirhoseinsadeghi** [KevinBatdorf/code-block-pro#339]
My site is in Farsi language with right to left direction. In all previous versions of the plugin, the codes in the front-end and back-end were correctly directed from left to right. In the latest version of the plugin (1.26.5), when I updated the plugin, all the codes in my site have found right to left direction.
https://i.postimg.cc/JnvVm20H/image.png

**Comment by KevinBatdorf** [comment]
Did this only happen when you went back to edit the content? Or did it suddenly happen to all your code blocks?

**Comment by amirhoseinsadeghi** [comment]
backend (edit post in Gutenberg) 👇
https://i.postimg.cc/mgpG8k4S/image.png


front-end (Display on the front of the site) 👇
https://i.postimg.cc/FHRMdvSk/image.png

As soon as I updated the plugin and referred to some posts on the front of the site, I saw that, unlike in the past, unfortunately, all the codes are displayed in a right-to-left direction. While in all the previous versions of the plugin, I did not have this problem and all the codes were correctly displayed from left to right.

As you can see in the first screenshot, this problem does not exist when editing the post in Gutenberg and the codes are left to right, but in the frontend they are right to left.

**Comment by KevinBatdorf** [comment]
It actually was an issue with an RTL webpack plugin WordPress added recently. Will release a fix in about 20min

**Comment by amirhoseinsadeghi** [comment]
This problem has returned in the recent version update (**1.26.7**), please fix it.

**Comment by KevinBatdorf** [comment]
I'll look into it now. thanks for letting me know

**Comment by KevinBatdorf** [comment]
Any way you can share a URL? It seems fine when I test it out on my own site

**Comment by amirhoseinsadeghi** [comment]
My site is in **Farsi language** with **right to left direction**. In all previous versions of the plugin, the codes in the front-end and back-end were correctly directed from **left to right**. In the latest version of the plugin (**1.26.7**), when I updated the plugin, all the codes in my site have found **right to left direction**.
https://i.postimg.cc/K8xh4zxh/image.png
and
https://i.postimg.cc/NjJCYf04/image.png

**Comment by KevinBatdorf** [comment]
I switched my language to Farsi and it was loading fine for me. The code from the last fix 6 months ago is still there, so I'll have to reproduce it to be able to fix it. 

If you can share a URL I can look at the CSS to see what happened. Or if you downgraded the plugin, can you try to figure out what CSS is overriding it?

**Comment by KevinBatdorf** [comment]
https://github.com/user-attachments/assets/d585025c-c329-4071-8ac6-6f9b68e53144

**Comment by amirhoseinsadeghi** [comment]
> I switched my language to Farsi and it was loading fine for me. The code from the last fix 6 months ago is still there, so I'll have to reproduce it to be able to fix it.
> 
> If you can share a URL I can look at the CSS to see what happened. Or if you downgraded the plugin, can you try to figure out what CSS is overriding it?

[Link](https://webzoj.com/blog/stop-spam-comments-in-wordpress/)

**Comment by KevinBatdorf** [comment]
The link helped thanks! I'll fix it today. If you want to fix it on your site, you can either downgrade, or do into the plugin `build` folder and delete the rtl stylesheets that were generated

**Comment by KevinBatdorf** [comment]
I just made the release so you should be able to update now. I also added an e2e test so something like this shouldn't happen again.

**Comment by amirhoseinsadeghi** [comment]
You are really welcome, thank you for your quick and good follow-up and support, your plugin is amazing and I love it so much
I updated the plugin and the problem was completely resolved, well done to you for having such a light, fast and efficient plugin and for constantly improving it
Thank you very much
