### ISSUE TITLE
Spacing issue with Typology theme

### ISSUE THREAD

**Issue by ccjx** [KevinBatdorf/code-block-pro#341]
Hi there

I've noticed that there is a spacing issue with the Typology theme (https://themeforest.net/item/typology-text-based-minimal-wordpress-blog-theme/19547842).

<img width="792" alt="image" src="https://github.com/user-attachments/assets/97a62d43-76b9-4858-985e-cf4505049abf">

I've spoken to their support and we had to add the following CSS customizations in order to fix the issue. Their feedback was that Code Block Pro does not use the standard css block classes. Hope you can resolve this for future users =).

```
.wp-block-kevinbatdorf-code-block-pro{
	margin-bottom: 3.6rem;
}
@media (max-width: 680px) {
	.wp-block-kevinbatdorf-code-block-pro {
		margin: 0 0 2rem;
	}
}
```

**Comment by KevinBatdorf** [comment]
Hey thanks for the feedback. Any idea which class is missing? I don't think I change anything there from what WordPress provides. Would be happy to fix it.

**Comment by ccjx** [comment]
The support team didn't share, I've taken a look through your plugin and it seems you already handle the `useBlockProps()` requirement in your `<div>`, so I'm not sure where the issue is. I'm assuming the `useBlockProps()` will inject the necessary margins based on the current theme and settings (I'm not familiar with Wordpress plugin dev).

https://github.com/KevinBatdorf/code-block-pro/blob/964c8f7ce87f5560e7151372c4e96200fb87487d/src/front/BlockOutput.tsx#L49

**Comment by KevinBatdorf** [comment]
Yeah I'm not sure what they are referring to.
