### ISSUE TITLE
Code Block Pro Stopped Working

### ISSUE THREAD

**Issue by paulsofts** [KevinBatdorf/code-block-pro#343]
Till last week, the plugin was working smoothly, but now what happens I don't know. I have activated and deactivated, even deleted and re-instated it a couple of times. Still showing the same error.
![image](https://github.com/user-attachments/assets/070692fa-621b-41a0-b47f-d63341ee910d)

**Comment by KevinBatdorf** [comment]
The plugin is active, right? 

Is your server out of disk space maybe?  Can you go and manually check the files are actually there?

**Comment by paulsofts** [comment]
Yes, it is active and also updated to the latest version.
![image](https://github.com/user-attachments/assets/4a5037c3-93da-477b-ac2f-dbe2cbc3f1d0)

**Comment by KevinBatdorf** [comment]
That error is from WordPress because it can't find the files. It's not an error I've added. Can you login to your server and confirm all the files are there? 

Another thing to try is to disable all other plugins for a moment to see if there's a conflict. If there is I can look into that.

**Comment by paulsofts** [comment]
Currently, it is installed and active. But if I'm trying to search it to add in a post, it says that it is available to install, and on clicking it, it gives the error.

![image](https://github.com/user-attachments/assets/007ad00b-0122-4f71-a2b9-a9baba046c6f)

**Error:**
![image](https://github.com/user-attachments/assets/25a4097c-9512-44f2-9023-aa1ebfbb32b6)

**Comment by KevinBatdorf** [comment]
Did you mean to post a comment?

**Comment by paulsofts** [comment]
@KevinBatdorf Hey, its resolved. I need to update WordPress and all other plugins to the latest version.😊

**Comment by KevinBatdorf** [comment]
Ok sounds good. Glad you got it working
