### ISSUE TITLE
With PJAX enabled, the Line highlighting is not working

### ISSUE THREAD

**Issue by xiaomoy** [KevinBatdorf/code-block-pro#94]
With PJAX enabled, the Line highlighting is not working.
I heard that enabling PJAX will cause JS not to load.
`
window.pjaxLoaded = function(){
	//This code is executed every time the page jumps
}
`
Here's the solution I found. How do I fill in the code?

**Comment by KevinBatdorf** [comment]
Hey @xiaomoy sorry I just saw this. Can you try the latest version of the plugin I just released and let me know? If not, can you share a URL?

**Comment by xiaomoy** [comment]
> Hey @xiaomoy sorry I just saw this. Can you try the latest version of the plugin I just released and let me know? If not, can you share a URL?
The update did not address that issue.
I'll send you the link via email later.


Instead, there are some problems with the Theme.
![image](https://user-images.githubusercontent.com/43872911/210484958-760ed392-3785-4195-b6ad-c1871e4419ea.png)

**Comment by xiaomoy** [comment]
![image](https://user-images.githubusercontent.com/43872911/210485802-331129a7-21d4-4e27-9402-8ea2a3788fde.png)

**Comment by KevinBatdorf** [comment]
I'll need to look into that now. Thank you for reporting it

**Comment by xiaomoy** [comment]
The detailed problems of PJAX have been sent to you by email👌

**Comment by KevinBatdorf** [comment]
In the next version I will add the init function to the global scope. Can you trigger this somehow in PJAX? Maybe like this?

```js
$(document).on('pjax:complete', function() {
  window.codeBlockProInit()
})
```

**Comment by KevinBatdorf** [comment]
This is live now if you want to give it a try. You can add this code with a JS plugin I think. I'm not sure which is a good one but if you have trouble with it just let me know. I'll close the issue here for now but please reply as needed.

**Comment by ZiXia1** [comment]
> In the next version I will add the init function to the global scope. Can you trigger this somehow in PJAX? Maybe like this?

Very well. He's working normally.

**Comment by KevinBatdorf** [comment]
NIce! 🙌

If you have time and can leave a review on the plugin that will help with ranking higher :)

https://wordpress.org/support/plugin/code-block-pro/reviews/#new-post
