### ISSUE TITLE
C# 11 Raw String Literals are not yet supported.

### ISSUE THREAD

**Issue by MarkBrainfire** [KevinBatdorf/code-block-pro#95]
Are there any plans to upgrade this wonderful WordPress block to support features in C# 11 such as raw literal strings?  For example, in the C_SpecialCharacters constant below the single quote in the middle of the string is taken as the end of the string as the new triple quotes enclosing syntax is not yet recognized.

![image](https://user-images.githubusercontent.com/78389339/210196150-9bb3b359-fac8-4b94-a22c-750ead21257a.png)

I very much appreciate your work developing this WordPress plugin.

**Comment by KevinBatdorf** [comment]
Hey @MarkBrainfire thanks for bringing this up. I'll update it in the next release this week.

**Comment by KevinBatdorf** [comment]
Can you try in the latest release? 1.11.0

![Screen Shot 2023-01-03 at 11 26 09 PM](https://user-images.githubusercontent.com/1478421/210484534-0fb5e1cd-3983-491d-885f-8e37d7a3321c.png)

**Comment by KevinBatdorf** [comment]
Actually I need to revert this change but will follow up asap. There was an error with the rendering on some servers.

**Comment by KevinBatdorf** [comment]
Okay sorry for the multiple updates. There was an issue with the renderer where streaming the wasm file caused some server configurations to fail to load the grammar file. I updated it just now in v1.11.2 so assuming there are no issues now the string should be parsed correctly now :) 

Reopen if you still have an issue with it. Thanks again for the report on this.
